additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: ocp.upi.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: %%WORKER_REPLICAS%%
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: %%MASTER_REPLICAS%%
metadata:
  creationTimestamp: null
  name: att-az
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: %%MACHINE_NET%%
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: arm-ocp-upi
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: eastus
publish: External
pullSecret: %%PULL_SECRET%%
sshKey: %%SSH_KEY%%
